name: server
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  shelf: ^1.1.0
  shelf_static: ^1.0.0
  shelf_router: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
